name: ltsv
author: Tomotaka Ito <tomotaka.ito@gmail.com>
homepage: https://github.com/tomotaka/dart-ltsv
description: LTSV(Labeled Tab-separated Values) format parser/dumper
version: 1.2.0
dev_dependencies:
  unittest: ">=0.11.0+3 <0.12.0"



